---
abstract: 'Powerful, high-performance templating for the web and beyond'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::Class::Most: 0
  Test::LongString: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mason
no_index:
  directory:
    - eg
    - lib/Mason/t
    - lib/Mason/Test
    - lib/Mason/Plugin/Defer
    - lib/Mason/Plugin/DollarDot
    - lib/Mason/Plugin/LvalueAttributes
    - lib/Mason/Plugin/TidyObjectFiles
  file:
    - lib/Mason/Util.pm
requires:
  Capture::Tiny: 0
  Class::Load: 0
  Class::Unload: 0
  Devel::GlobalDestruction: 0
  Exception::Class: 0
  File::Spec: 0
  File::Temp: 0
  Guard: 0
  IPC::System::Simple: 0
  JSON: 0
  Log::Any: 0.08
  Memoize: 0
  Method::Signatures::Simple: 0
  Moose: 1.15
  MooseX::HasDefaults: 0.03
  MooseX::StrictConstructor: 0.13
  Scalar::Util: 1.01
  Try::Tiny: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Mason
  repository: git://github.com/jonswar/perl-mason.git
version: 2.22
