---
abstract: 'Powerful, high-performance templating for the web and beyond'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::Class::Most: 0
  Test::LongString: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mason
no_index:
  directory:
    - lib/Mason/t
    - lib/Mason/Test
  file:
    - lib/Mason/Util.pm
requires:
  Capture::Tiny: 0
  Class::Unload: 0
  File::Temp: 0
  Guard: 0
  IPC::System::Simple: 0
  JSON: 0
  Log::Any: 0
  Memoize: 0
  Method::Signatures::Simple: 0
  Moose: 0.95
  MooseX::HasDefaults: 0
  MooseX::StrictConstructor: 0
  Scalar::Util: 1.01
  Try::Tiny: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Mason
  repository: git://github.com/jonswar/perl-mason.git
version: 2.00
